"""Add subscriber_id column to users table

Revision ID: 682e6dcf2a11
Revises: e90271175b14
Create Date: 2024-09-27 00:20:58.878237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682e6dcf2a11'
down_revision: Union[str, None] = 'e90271175b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auctions', 'current_price',
                    existing_type=sa.INTEGER(),
                    type_=sa.Float(),
                    existing_nullable=False)

    with op.batch_alter_table('auctions') as batch_op:
        batch_op.alter_column('end_time',
                              existing_type=sa.VARCHAR(length=120),
                              type_=sa.DateTime(),
                              existing_nullable=False,
                              postgresql_using='end_time::timestamp without time zone')

    op.add_column('users', sa.Column('subscriber_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'subscribers', ['subscriber_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'subscriber_id')

    with op.batch_alter_table('auctions') as batch_op:
        batch_op.alter_column('end_time',
                              existing_type=sa.DateTime(),
                              type_=sa.VARCHAR(length=120),
                              existing_nullable=False)

    op.alter_column('auctions', 'current_price',
                    existing_type=sa.Float(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    # ### end Alembic commands ###